# Site settings
title: Cindy Lai's Data Treasure Trove
header-img: img/home-bg.jpg
email: CynthiaLai1996@gmail.com
description: Cindy Lai's STA 141B portfolio site 
baseurl: ""
url: "https://laic5.github.io"
github_username:  laic5
email_username: CynthiaLai1996@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
