# Site settings
title: Cindy Lai STAT 141b
header-img: img/home-bg.jpg
email: cynlai@ucdavis.edu
description: Cindy Lai's STAT 141B portfolio site 
baseurl: ""
url: "https://laic5.github.io"
github_username:  laic5
email_username: cynlai@ucdavis.edu

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
